### ISSUE TITLE
yi dome 1080p

### ISSUE THREAD

**Issue by garciamaleno** [fjramirez1987/PTZ-YCC365#4]
buenas, tengo una camara submarca de xiaomi (yi dome 1080p), saca el video en rtsp y se ve bien en home assistant con todo el codigo que pones pero las flechas no funcionan habria alguna manera de pasarlo a mpeg o otra forma para que me funcione los controles de pan tilt.

nota : estoy empezando en esto, he buscando informacion pero no veo nada

gracias

**Comment by fjramirez1987** [comment]
Este componente no obtiene el video de las cámaras, solo llama a una función para mover las cámaras compatibles.
