### ISSUE TITLE
Issue adding camera to the motioneye

### ISSUE THREAD

**Issue by elik745i** [fjramirez1987/PTZ-YCC365#5]
Great work first of all!
Strange but when I try to add my ycc365 plus camera into motioneye I get this error:
![image](https://user-images.githubusercontent.com/17794736/108413788-df063280-7244-11eb-96a5-036763323d79.png)

**Comment by fjramirez1987** [comment]
Hello, this component has nothing to do with Motioneye.  You must ask in the appropriate repository.  Greetings.

**Comment by mimokini** [comment]
rtsp://10.10.10.30:8001/
